# Generated by Django 5.1 on 2024-09-04 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('birth_date', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=20)),
                ('preferences', models.CharField(max_length=500)),
            ],
        ),
    ]
